# FUNCAO PRINT FAZ UMA CHAMADA DE KERNEL PARA MOSTRAR CARACTERES NA TELA, E NAO RETORNA NADA.
# EM PYTHON, O OBJETO PASSADO COMO PARAMETRO NA FUNCAO PRINT, É RESPONSAVEL POR SE CONVERTER PARA STRING
# DE FORMA A SER IMPRESSO NA TELA.
print("Alo mundo")
